### ISSUE TITLE
Named dependency injection failing

### ISSUE THREAD

**Issue by brandonlamb** [micronaut-projects/micronaut-test#17]
We are using the `micronaut-jdbc-hikaricp` and both DB2 and postgres, along with MyBatis.

What we are seeing is that if we try to inject a `SqlSessionFactory` with a named qualifier in a test, it fails with the typical "more than one implementation found" error.

```kotlin
@MicronautTest
class MyTest {
  @Inject
  @Named("db2")
  lateinit var ssf: SqlSessionFactory
}
```

```yaml
---
datasources:
  db2:
    url: "jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=DB2;AUTO_RECONNECT=TRUE"
    username: sa
    password: ""
    driverClassName: org.h2.Driver

  pgsql:
    url: "jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=DB2;AUTO_RECONNECT=TRUE"
    username: sa
    password: ""
    driverClassName: org.h2.Driver

---
flyway:
  datasources:
    db2:
      locations: classpath:flyway
      clean-schema: true
```

And factory:

```kotlin
@Factory
class ConfigurationFactory {
  @Bean
  @Named("db2")
  fun createDb2(appConfig: AppConfig, @Named("db2") env: Environment): Configuration = create(appConfig, env)

  @Bean
  @Named("pgsql")
  fun createPgsql(appConfig: AppConfig, @Named("pgsql") env: Environment): Configuration = create(appConfig, env)
  //snip unimportant stuff
}
```

What I have done instead is written my test case as below, which works, but obviously not as expected

```kotlin
@MicronautTest
class ApiTest {
  @Inject
  lateinit var spec: RequestSpecification

  @Inject
  lateinit var ctx: ApplicationContext

//  @Inject
//  @Named("db2")
//  lateinit var ssf: SqlSessionFactory

  private fun ssf(): SqlSessionFactory = ctx.getBean(SqlSessionFactory::class.java, Qualifiers.byName("db2"))
}
```
